services:
  - type: web
    name: lyxene-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FRONTEND_URL
        value: https://frontend-self-five-87.vercel.app
      - key: NODE_ENV
        value: production
